# End command phrases
end_phrases = [
    "konec",
    "ukonči",
    "ukončit",
    "skonči",
    "skončit",
    "end"
]
# Help command phrases
help_phrases = [
    "nápověda",
    "nápovědu",
    "nápovědy",
    "pomoc",
    "help"
]
# Non-yes-no question phrases
non_yes_no = [
    "kolik",
    "počet",
    "jaká"
]
# Yes phrases
yes_phrases = [
    "ano",
    "jo",
    "samozřejmě",
    "určitě"
]
# No phrases
no_phrases = [
    "ne",
    "nechci",
    "nemám",
    "nebudu"
]

# Kraj.txt from SP3
places = [
    "Praha",
    "Praze",
    "Prahu",
    "Prahou",
    "Praho",
    "Prahy",
    "Ústecký kraj",
    "Ústeckého kraje",
    "Ústeckému kraji",
    "Ústeckým krajem",
    "Ústeckém kraji",
    "Ústecké krajiny",
    "Ústeckých krajů",
    "Ústeckými kraji",
    "Ústí nad Labem",
    "Ústím nad Labem",
    "Ústí",
    "Karlovarský kraj",
    "Karlovarského kraje",
    "Karlovarskému kraji",
    "Karlovarským krajem",
    "Karlovarském kraji",
    "Karlovarské krajiny",
    "Karlovarských krajů",
    "Karlovarskými kraji",
    "Karlovy Vary",
    "Karlovy Var",
    "Karlových Varů",
    "Karlových Varech",
    "Karlovým Varům",
    "Vary",
    "Varech",
    "Plzeňský kraj",
    "Plzeňského kraje",
    "Plzeňskému kraji",
    "Plzeňským krajem",
    "Plzeňském kraji",
    "Plzeňské krajiny",
    "Plzeňských krajů",
    "Plzeňskými kraji",
    "Plzeňsko",
    "Plzeňska",
    "Plzeňsku",
    "Plzeň",
    "Plzně",
    "Plzni",
    "Plzní",
    "Plzně",
    "Liberecký kraj",
    "Libereckého kraje",
    "Libereckému kraji",
    "Libereckým krajem",
    "Libereckém kraji",
    "Liberecké krajiny",
    "Libereckých krajů",
    "Libereckými kraji",
    "Liberec",
    "Liberci",
    "Libercem",
    "Královéhradecký kraj",
    "Královéhradeckého kraje",
    "Královéhradeckému kraji",
    "Královéhradeckým krajem",
    "Královéhradeckém kraji",
    "Královéhradecké krajiny",
    "Královéhradeckých krajů",
    "Královéhradeckými kraji",
    "Hradec Králové",
    "Hradci Králové",
    "Hradcem Králové",
    "Hradec",
    "Hradci",
    "Hradcem",
    "Jihočeský kraj",
    "Jihočeského kraje",
    "Jihočeskému kraji",
    "Jihočeským krajem",
    "Jihočeském kraji",
    "Jihočeské krajiny",
    "Jihočeských krajů",
    "Jihočeskými kraji",
    "České Budějovice",
    "Českých Budějovic",
    "Českým Budějovicím",
    "Českými Budějovicemi",
    "Českých Budějovic",
    "Budějovice",
    "Budějovic",
    "Budějovicím",
    "Budějovicemi",
    "Budějovic",
    "Budějky",
    "Budějkách",
    "Budějkami",
    "Moravskoslezský kraj",
    "Moravskoslezského kraje",
    "Moravskoslezskému kraji",
    "Moravskoslezským krajem",
    "Moravskoslezském kraji",
    "Moravskoslezské krajiny",
    "Moravskoslezských krajů",
    "Moravskoslezskými kraji",
    "Ostrava",
    "Ostravě",
    "Ostravou",
    "Olomoucký kraj",
    "Olomouckého kraje",
    "Olomouckému kraji",
    "Olomouckým krajem",
    "Olomouckém kraji",
    "Olomoucké krajiny",
    "Olomouckých krajů",
    "Olomouckými kraji",
    "Olomouc",
    "Olomouci",
    "Olomoucem",
    "Olomoucí",
    "Pardubický kraj",
    "Pardubického kraje",
    "Pardubickému kraji",
    "Pardubickým krajem",
    "Pardubickém kraji",
    "Pardubické krajiny",
    "Pardubických krajů",
    "Pardubickými kraji",
    "Pardubice",
    "Pardubicím",
    "Pardubicemi",
    "Vysočinou kraj",
    "Vysočině kraje",
    "Vysočinou kraji",
    "Vysočině krajem",
    "Vysočinách kraje",
    "Vysočina",
    "Vysočiny",
    "Vysočině",
    "Vysočinou",
    "Jihlava",
    "Jihlavě",
    "Jihlavou",
    "Jihomoravský kraj",
    "Jihomoravském kraji",
    "Jihomoravského kraje",
    "Brno",
    "Brnu",
    "Brně",
    "Brnem",
    "Zlínský kraj",
    "Zlínského kraje",
    "Zlínskému kraji",
    "Zlínským krajem",
    "Zlínském kraji",
    "Zlínské krajiny",
    "Zlínských krajů",
    "Zlínskými kraji",
    "Zlín",
    "Zlínu",
    "Zlíně",
    "Zlínem",
    "Středočeský kraj",
    "Středočeského kraje",
    "Středočeskému kraji",
    "Středočeským krajem",
    "Středočeském kraji",
    "Středočeské krajiny",
    "Středočeských krajů",
    "Středních Čech",
    "Středních Čechách",
    "Středních Čechám",
    "Středními Čechami",
    "Česku",
    "České republice",
    "Čechách",
    "všude",
    "republika",
    "republice",
    "ČR"
]
# Create map for API names of places
places_api_map = {
    "hl. m. Praha": [
        "Praha",
        "Praze",
        "Prahu",
        "Prahou",
        "Praho",
        "Prahy"
    ],
    "Ústecký": [
        "Ústecký kraj",
        "Ústeckého kraje",
        "Ústeckému kraji",
        "Ústeckým krajem",
        "Ústeckém kraji",
        "Ústecké krajiny",
        "Ústeckých krajů",
        "Ústeckými kraji",
        "Ústí nad Labem",
        "Ústím nad Labem",
        "Ústí"
    ],
    "Karlovarský": [
        "Karlovarský kraj",
        "Karlovarského kraje",
        "Karlovarskému kraji",
        "Karlovarským krajem",
        "Karlovarském kraji",
        "Karlovarské krajiny",
        "Karlovarských krajů",
        "Karlovarskými kraji",
        "Karlovy Vary",
        "Karlovy Var",
        "Karlových Varů",
        "Karlových Varech",
        "Karlovým Varům",
        "Vary",
        "Varech"
    ],
    "Plzeňský": [
        "Plzeňský kraj",
        "Plzeňského kraje",
        "Plzeňskému kraji",
        "Plzeňským krajem",
        "Plzeňském kraji",
        "Plzeňské krajiny",
        "Plzeňských krajů",
        "Plzeňskými kraji",
        "Plzeňsko",
        "Plzeňska",
        "Plzeňsku",
        "Plzeň",
        "Plzně",
        "Plzni",
        "Plzní",
        "Plzně",
    ],
    "Liberecký": [
        "Liberecký kraj",
        "Libereckého kraje",
        "Libereckému kraji",
        "Libereckým krajem",
        "Libereckém kraji",
        "Liberecké krajiny",
        "Libereckých krajů",
        "Libereckými kraji",
        "Liberec",
        "Liberci",
        "Libercem"
    ],
    "Královéhradecký": [
        "Královéhradecký kraj",
        "Královéhradeckého kraje",
        "Královéhradeckému kraji",
        "Královéhradeckým krajem",
        "Královéhradeckém kraji",
        "Královéhradecké krajiny",
        "Královéhradeckých krajů",
        "Královéhradeckými kraji",
        "Hradec Králové",
        "Hradci Králové",
        "Hradcem Králové",
        "Hradec",
        "Hradci",
        "Hradcem"
    ],
    "Jihočeský": [
        "Jihočeský kraj",
        "Jihočeského kraje",
        "Jihočeskému kraji",
        "Jihočeským krajem",
        "Jihočeském kraji",
        "Jihočeské krajiny",
        "Jihočeských krajů",
        "Jihočeskými kraji",
        "České Budějovice",
        "Českých Budějovic",
        "Českým Budějovicím",
        "Českými Budějovicemi",
        "Českých Budějovic",
        "Budějovice",
        "Budějovic",
        "Budějovicím",
        "Budějovicemi",
        "Budějovic",
        "Budějky",
        "Budějkách",
        "Budějkami"
    ],
    "Moravskoslezský": [
        "Moravskoslezský kraj",
        "Moravskoslezského kraje",
        "Moravskoslezskému kraji",
        "Moravskoslezským krajem",
        "Moravskoslezském kraji",
        "Moravskoslezské krajiny",
        "Moravskoslezských krajů",
        "Moravskoslezskými kraji",
        "Ostrava",
        "Ostravě",
        "Ostravou"
    ],
    "Olomoucký": [
        "Olomoucký kraj",
        "Olomouckého kraje",
        "Olomouckému kraji",
        "Olomouckým krajem",
        "Olomouckém kraji",
        "Olomoucké krajiny",
        "Olomouckých krajů",
        "Olomouckými kraji",
        "Olomouc",
        "Olomouci",
        "Olomoucem",
        "Olomoucí"
    ],
    "Pardubický": [
        "Pardubický kraj",
        "Pardubického kraje",
        "Pardubickému kraji",
        "Pardubickým krajem",
        "Pardubickém kraji",
        "Pardubické krajiny",
        "Pardubických krajů",
        "Pardubickými kraji",
        "Pardubice",
        "Pardubicím",
        "Pardubicemi"
    ],
    "Vysočina": [
        "Vysočinou kraj",
        "Vysočině kraje",
        "Vysočinou kraji",
        "Vysočině krajem",
        "Vysočinách kraje",
        "Vysočina",
        "Vysočiny",
        "Vysočině",
        "Vysočinou",
        "Jihlava",
        "Jihlavě",
        "Jihlavou",
    ],
    "Jihomoravský": [
        "Jihomoravský kraj",
        "Jihomoravském kraji",
        "Jihomoravského kraje",
        "Brno",
        "Brnu",
        "Brně",
        "Brnem"
    ],
    "Zlínský": [
        "Zlínský kraj",
        "Zlínského kraje",
        "Zlínskému kraji",
        "Zlínským krajem",
        "Zlínském kraji",
        "Zlínské krajiny",
        "Zlínských krajů",
        "Zlínskými kraji",
        "Zlín",
        "Zlínu",
        "Zlíně",
        "Zlínem"
    ],
    "Středočeský": [
        "Středočeský kraj",
        "Středočeského kraje",
        "Středočeskému kraji",
        "Středočeským krajem",
        "Středočeském kraji",
        "Středočeské krajiny",
        "Středočeských krajů",
        "Středních Čech",
        "Středních Čechách",
        "Středních Čechám",
        "Středními Čechami"
    ],
    "ČR": [
        "Česku",
        "České republice",
        "Čechách",
        "všude",
        "republika",
        "republice",
        "ČR"
    ]
}
places_speech_map = {
    "hl. m. Praha": "v Praze",
    "Ústecký": "v Ústeckém kraji",
    "Karlovarský": "v Karlovarském kraji",
    "Plzeňský": "v Plzeňském kraji",
    "Liberecký": "v Libereckém kraji",
    "Královéhradecký": "v Královéhradeckém kraji",
    "Jihočeský": "v Jihočeském kraji",
    "Moravskoslezský": "v Moravskoslezském kraji",
    "Olomoucký": "v Olomouckém kraji",
    "Pardubický": "v Pardubickém kraji",
    "Vysočina": "na Vysočině",
    "Jihomoravský": "v Jihomoravském kraji",
    "Zlínský": "ve Zlínském kraji",
    "Středočeský": "ve Středočeském kraji",
    "ČR": "v České republice"
}
# Create reversed map for later use (API purpose)
places_api_map_reversed = {place: api_place for api_place, places in places_api_map.items() for place in places}

# Nehoda.txt from SP3
accidents = [
    "nehoda",
    "nehody",
    "nehod",
    "nehodám",
    "nehodě",
    "nehodu",
    "nehodách",
    "nehodami",
    "nehodou",
    "dopravní nehoda",
    "dopravní nehody",
    "dopravních nehod",
    "dopravní nehodou",
    "počet mrtvých",
    "počty mrtvých",
    "mrtví",
    "mrtvých",
    "mrtvých osob",
    "mrtvých lidí",
    "mrtví lidé",
    "mrtvé osoby",
    "smrťák",
    "smrťáky",
    "smrťákem",
    "smrťáků",
    "úmrtí",
    "úmrtím",
    "úmrtích",
    "úmrtí lidí",
    "úmrtí osob",
    "někdo zemřel",
    "zemřel",
    "těžce zraněných",
    "těžce zranění",
    "těžce zraněných",
    "těžkých zranění",
    "lehce zraněných",
    "lehce zranění",
    "lehce zraněných",
    "případy jízdy pod vlivem",
    "případy řízení pod vlivem alkoholu",
    "případy jízdy pod vlivem alkoholu",
    "případy jízdy pod vlivem drog",
    "případy nedání přednosti",
    "případy nedání přednosti v jízdě",
    "případy nedání přednosti v silničním provozu",
    "případy nesprávného předjíždění",
    "případy nesprávného předjíždění vozidel",
    "případy nepřiměřené rychlosti",
    "případy rychlostních přestupků",
    "případy nesprávného způsobu jízdy",
    "případy jiných příčin dopravních nehod",
    "jízdy pod vlivem",
    "řízení pod vlivem alkoholu",
    "jízdy pod vlivem alkoholu",
    "jízdy pod vlivem drog",
    "nedání přednosti",
    "nedání přednosti v jízdě",
    "nedání přednosti v silničním provozu",
    "nesprávného předjíždění",
    "nesprávného předjíždění vozidel",
    "nepřiměřené rychlosti",
    "rychlostních přestupků",
    "nesprávného způsobu jízdy",
    "jiných příčin dopravních nehod",
    "další příčiny dopravních nehod",
    "výše škod",
    "škody na majetku",
    "škoda",
    "škody",
    "škod",
    "škodou",
    "materiální škoda",
    "materiální škody",
    "materiálních škod",
    "materiální škodou",
    "jiná příčina",
    "jiných příčin",
    "jiné příčiny",
    "jinou příčinou",
    "požití omamné a psychotropní látky",
    "požití drog",
    "požití drogy",
    "požitím omamné a psychotropní látky",
    "požitím drog",
    "požitím drogy"
]
# Create map for API names of places
accidents_api_map = {
    "PN": [
        "nehoda",
        "nehody",
        "nehod",
        "nehodám",
        "nehodě",
        "nehodu",
        "nehodách",
        "nehodami",
        "nehodou",
        "dopravní nehoda",
        "dopravní nehody",
        "dopravních nehod",
        "dopravní nehodou"
    ],
    "M": [
        "počet mrtvých",
        "počty mrtvých",
        "mrtví",
        "mrtvých",
        "mrtvých osob",
        "mrtvých lidí",
        "mrtví lidé",
        "mrtvé osoby",
        "smrťák",
        "smrťáky",
        "smrťákem",
        "smrťáků",
        "úmrtí",
        "úmrtím",
        "úmrtích",
        "úmrtí lidí",
        "úmrtí osob",
        "někdo zemřel",
        "zemřel"
    ],
    "TR": [
        "těžce zraněných",
        "těžce zranění",
        "těžce zraněných",
        "těžkých zranění"
    ],
    "LR": [
        "lehce zraněných",
        "lehce zranění",
        "lehce zraněných"
    ],
    "Š": [
        "výše škod",
        "škody na majetku",
        "škoda",
        "škody",
        "škod",
        "škodou",
        "materiální škoda",
        "materiální škody",
        "materiálních škod",
        "materiální škodou",
    ],
    "NR": [
        "nepřiměřená rychlost",
        "rychlostních přestupků"
    ],
    "NPJ": [
        "nedání přednosti",
        "nedání přednosti v jízdě",
        "nedání přednosti v silničním provozu"
    ],
    "NP": [
        "nesprávné předjíždění",
        "nesprávné předjíždění vozidel"
    ],
    "NZJ": [
        "nesprávný způsob jízdy",
        "jiných příčin dopravních nehod"
    ],
    "JP": [
        "jiná příčina",
        "jiných příčin",
        "jiné příčiny",
        "jinou příčinou"
    ],
    "PVA": [
        "případy jízdy pod vlivem",
        "řízení pod vlivem alkoholu",
        "jízdy pod vlivem alkoholu",
        "jízdy pod vlivem drog"
    ],
    "OPL": [
        "požití omamné a psychotropní látky",
        "požití drog",
        "požití drogy",
        "požitím omamné a psychotropní látky",
        "požitím drog",
        "požitím drogy"
    ]
}
accidents_speech_map = {
    "PN": "počet nehod",
    "M": "počet mrtvých",
    "TR": "počet těžce zraněných",
    "LR": "počet lehce zraněných",
    "Š": "výše škod",
    "NR": "počet nepřiměřené rychlosti",
    "NPJ": "počet nedání přednosti",
    "NP": "počet nesprávného předjíždění",
    "NZJ": "počet nesprávného způsobu jízdy",
    "JP": "počet jiných příčin",
    "PVA": "počet případů jízdy pod vlivem",
    "OPL": "počet případů požití omamných látek"
}
# Create reversed map for later use (API purpose)
accidents_api_map_reversed = {accident: api for api, accidents in accidents_api_map.items() for accident in accidents}

# Den.txt Mesic.txt from SP3
days_and_time = [
    "pondělí",
    "pondělka",
    "pondělku",
    "pondělek",
    "pondělích",
    "pondělkem",
    "pondělky",
    "úterý",
    "úterka",
    "úterku",
    "úterek",
    "úterým",
    "úterých",
    "úterkem",
    "středa",
    "středy",
    "středu",
    "středě",
    "středou",
    "středo",
    "středěch",
    "středech",
    "středem",
    "středami",
    "středám",
    "čtvrtek",
    "čtvrteček",
    "čtvrtečka",
    "čtvrtečku",
    "čtvrtekem",
    "čtvrtečkem",
    "čtvrtec",
    "čtvrtky",
    "pátek",
    "pátku",
    "páteček",
    "pátekem",
    "pátkem",
    "pátečka",
    "pátečko",
    "pátečky",
    "sobota",
    "sobotu",
    "soboty",
    "sobotě",
    "sobotou",
    "sobot",
    "sobotám",
    "sobotách",
    "sobotkách",
    "sobotkám",
    "sobotku",
    "neděle",
    "neděli",
    "nedělech",
    "nedělí",
    "nedělích",
    "nedělíků",
    "nedělím",
    "nedělku",
    "nedělem",
    "nedělní",
    "dnes",
    "dneska",
    "dnes",
    "dneska",
    "dneška",
    "dnešního dne",
    "včera",
    "předvčírem",
    "předevčírem",
    "předvčerejškem",
    "předevčerejškem",
    "týden",
    "týdne",
    "týdně",
    "týdnem",
    "týdenní",
    "měsíc",
    "měsíce",
    "měsíci",
    "měsícem",
    "měsíční",
    "rok",
    "roku",
    "roce",
    "rokem",
    "roční",
    "letos",
    "loni",
    "vloni"
]
months = [
    "leden",
    "lednu",
    "lednem",
    "lednu",
    "únor",
    "únoru",
    "únorem",
    "únoru",
    "březen",
    "březnu",
    "březnem",
    "březnu",
    "duben",
    "dubnu",
    "dubnem",
    "dubnu",
    "květen",
    "květnu",
    "květnem",
    "květnu",
    "červen",
    "červnu",
    "červnem",
    "červnu",
    "červenec",
    "červenci",
    "červencem",
    "červenci",
    "srpen",
    "srpnu",
    "srpnem",
    "srpnu",
    "září",
    "září",
    "zářím",
    "září",
    "říjen",
    "říjnu",
    "říjnem",
    "říjnu",
    "listopad",
    "listopadu",
    "listopadem",
    "listopadu",
    "prosinec",
    "prosinci",
    "prosincem",
    "prosinci"
]
time_array = days_and_time + months
# Create map for times
time_map = {
    "mon": [
        "pondělí",
        "pondělka",
        "pondělku",
        "pondělek",
        "pondělích",
        "pondělkem",
        "pondělky"
    ],
    "tue": [
        "úterý",
        "úterka",
        "úterku",
        "úterek",
        "úterým",
        "úterých",
        "úterkem"
    ],
    "wed": [
        "středa",
        "středy",
        "středu",
        "středě",
        "středou",
        "středo",
        "středěch",
        "středech",
        "středem",
        "středami",
        "středám"
    ],
    "thu": [
        "čtvrtek",
        "čtvrteček",
        "čtvrtečka",
        "čtvrtečku",
        "čtvrtekem",
        "čtvrtečkem",
        "čtvrtec",
        "čtvrtky"
    ],
    "fri": [
        "pátek",
        "pátku",
        "páteček",
        "pátekem",
        "pátkem",
        "pátečka",
        "pátečko",
        "pátečky"
    ],
    "sat": [
        "sobota",
        "sobotu",
        "soboty",
        "sobotě",
        "sobotou",
        "sobot",
        "sobotám",
        "sobotách",
        "sobotkách",
        "sobotkám",
        "sobotku"
    ],
    "sun": [
        "neděle",
        "neděli",
        "nedělech",
        "nedělí",
        "nedělích",
        "nedělíků",
        "nedělím",
        "nedělku",
        "nedělem",
        "nedělní"
    ],
    "today": [
        "dnes",
        "dneska",
        "dnes",
        "dneska",
        "dneška",
        "dnešního dne"
    ],
    "yesterday": [
        "včera"
    ],
    "daybeforeyesterday": [
        "předvčírem",
        "předevčírem",
        "předvčerejškem",
        "předevčerejškem"
    ],
    "week": [
        "týden",
        "týdne",
        "týdně",
        "týdnem",
        "týdenní"
    ],
    "MONth": [  # "MON" is capital, because "mon" is for monday (I need these keys to be prefix free!)
        "měsíc",
        "měsíce",
        "měsíci",
        "měsícem",
        "měsíční"
    ],
    "year": [
        "rok",
        "roku",
        "roce",
        "rokem",
        "roční"
    ],
    "thisyear": [
        "letos"
    ],
    "lastyear": [
        "loni",
        "vloni"
    ],
    "jan": [
        "leden",
        "lednu",
        "lednem",
        "lednu"
    ],
    "feb": [
        "únor",
        "únoru",
        "únorem",
        "únoru"
    ],
    "mar": [
        "březen",
        "březnu",
        "březnem",
        "březnu"
    ],
    "apr": [
        "duben",
        "dubnu",
        "dubnem",
        "dubnu"
    ],
    "may": [
        "květen",
        "květnu",
        "květnem",
        "květnu"
    ],
    "jun": [
        "červen",
        "červnu",
        "červnem",
        "červnu"
    ],
    "jul": [
        "červenec",
        "červenci",
        "červencem",
        "červenci"
    ],
    "aug": [
        "srpen",
        "srpnu",
        "srpnem",
        "srpnu"
    ],
    "sep": [
        "září",
        "září",
        "zářím",
        "září"
    ],
    "oct": [
        "říjen",
        "říjnu",
        "říjnem",
        "říjnu"
    ],
    "nov": [
        "listopad",
        "listopadu",
        "listopadem",
        "listopadu"
    ],
    "dec": [
        "prosinec",
        "prosinci",
        "prosincem",
        "prosinci"
    ]
}
day_keys = [
    "today",
    "yesterday",
    "daybeforeyesterday"
]
week_keys = [
    "mon",
    "tue",
    "wed",
    "thu",
    "fri",
    "sat",
    "sun",
    "week"
]
month_keys = [
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
    "MONth"
]
year_keys = [
    "year",
    "thisyear",
    "lastyear"
]
# Create reversed map for later use (API purpose)
time_map_reversed = {time: key for key, values in time_map.items() for time in values}

# Den_dekorator.txt from SP3
time_decorators = [
    "tento",
    "tohoto",
    "tomuto",
    "tentéž",
    "minulý",
    "minulá",
    "minulé",
    "minulého",
    "minulému",
    "minulému",
    "minulým",
    "minulou",
    "předminulý",
    "předminulá",
    "předminulé",
    "předminulého",
    "předminulému",
    "předminulému",
    "předminulým",
    "předminulou",
    "nedávný",
    "nedávného",
    "nedávnému",
    "nedávným",
    "aktuální",
    "aktuálního",
    "aktuálním",
    "aktuálnímu",
    "poslední",
    "posledního",
    "poslednímu",
    "posledním",
    "předchozí",
    "předchozího",
    "předchozímu",
    "předchozím",
    "předchozích",
    "předchozí"
]
# Create map for times
time_decorators_map = {
    "this": [
        "tento",
        "tohoto",
        "tomuto",
        "tentéž",
        "aktuální",
        "aktuálního",
        "aktuálním",
        "aktuálnímu",
        "nedávný",
        "nedávného",
        "nedávnému",
        "nedávným"
    ],
    "last": [
        "minulý",
        "minulá",
        "minulé",
        "minulého",
        "minulému",
        "minulému",
        "minulým",
        "minulou",
        "poslední",
        "posledního",
        "poslednímu",
        "posledním",
        "předchozí",
        "předchozího",
        "předchozímu",
        "předchozím",
        "předchozích"
    ],
    "lastlast": [
        "předminulý",
        "předminulá",
        "předminulé",
        "předminulého",
        "předminulému",
        "předminulému",
        "předminulým",
        "předminulou"
    ],
}
# Create reversed map for later use (API purpose)
time_decorators_map_reversed = {time: key for key, values in time_decorators_map.items() for time in values}
